BEGIN;

DROP TABLE IF EXISTS user_in_train;
DROP TABLE IF EXISTS user_friends;
DROP TABLE IF EXISTS train_to_loc;
DROP TABLE IF EXISTS user_send_msg;
DROP TABLE IF EXISTS user_in_net;
DROP TABLE IF EXISTS trains; 
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS network;
DROP TABLE IF EXISTS users;

COMMIT;